version: '3.9'

services:

  db:
    image: postgres
    restart: on-failure
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"

  dbteste:
    container_name: db_teste
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: db_teste
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5431:5432"
      
volumes:
  dbdata:
