version: '3.9'

services:

  db:
    image: postgres
    restart: on-failure
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devtraining
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
      
volumes:
  dbdata:
